my.object:
  string: string
  integer: 100

osiam:
  endpoint: http://localhost:8999
  client:
    id: example-client
    secret: secret

management:
  context-path: /management
  security.enabled: false
